
#ifndef KLIN_AUTOGENERATED_CPP_HEADER_H
#define KLIN_AUTOGENERATED_CPP_HEADER_H

#include <any>
#include <string>
#include <QObject>
#include <QString>
#include <QVariant>
#include "KT.h"
template<typename T> void mainSet(const std::string &key, T value);

class API: public QObject {
    Q_OBJECT

    public slots:

        void mainSet(const QString &key, const QVariant &value);

};

class MainContext {
    public:
        MainContext(KTRef(MainContext) ctx): ctx(ctx) { }


        bool didClickChangeText();

        bool didLaunch();

        bool didSetup();

        QString greetingText() const &;

        bool isVisible();


    private:
        KTRef(MainContext) ctx;
};

class MainEffectRegistry {
    public:
        static void processOneliners();
        static void registerOneliners(
            KTRef(KDController) ctrl,
            const std::vector<std::any> &items
        );

    private:
        static std::vector<std::any> _items;
};

// Special structure to reference keys with a compile time check
struct FStruct {
    static inline constexpr const char *didClickChangeText = "didClickChangeText";
    static inline constexpr const char *didLaunch = "didLaunch";
    static inline constexpr const char *didSetup = "didSetup";
    static inline constexpr const char *greetingText = "greetingText";
    static inline constexpr const char *isVisible = "isVisible";
    static inline constexpr const char *none = "none";

};
inline FStruct F;

// Special structure to reference keys in QML
class FObj: public QObject {
    Q_OBJECT
    Q_PROPERTY(QString didClickChangeText READ key_didClickChangeText CONSTANT)
    Q_PROPERTY(QString didLaunch READ key_didLaunch CONSTANT)
    Q_PROPERTY(QString didSetup READ key_didSetup CONSTANT)
    Q_PROPERTY(QString greetingText READ key_greetingText CONSTANT)
    Q_PROPERTY(QString isVisible READ key_isVisible CONSTANT)
    Q_PROPERTY(QString none READ key_none CONSTANT)


    public:
        FObj(): QObject() { }
        QString key_didClickChangeText() const { return F.didClickChangeText; }
        QString key_didLaunch() const { return F.didLaunch; }
        QString key_didSetup() const { return F.didSetup; }
        QString key_greetingText() const { return F.greetingText; }
        QString key_isVisible() const { return F.isVisible; }
        QString key_none() const { return F.none; }

};

#endif // KLIN_AUTOGENERATED_CPP_HEADER_H
