
#ifndef KLIN_AUTOGENERATED_CPP_HEADER_H
#define KLIN_AUTOGENERATED_CPP_HEADER_H

#include <any>
#include <string>
#include <QObject>
#include <QString>
#include <QVariant>
#include "KT.h"
template<typename T> void mainSet(const std::string &key, T value);

class API: public QObject {
    Q_OBJECT

    public slots:

        void mainSet(const QString &key, const QVariant &value);

};

class MainContext {
    public:
        MainContext(KTRef(MainContext) ctx): ctx(ctx) { }


        bool didClickSaveText();

        bool didLaunch();

        QString didSelectTask() const &;

        bool didSetup();

        bool isVisible();

        QString saveString() const &;

        bool shouldSavaTasks();

        QString taskTitle() const &;


    private:
        KTRef(MainContext) ctx;
};

class MainEffectRegistry {
    public:
        static void processOneliners();
        static void registerOneliners(
            KTRef(KDController) ctrl,
            const std::vector<std::any> &items
        );

    private:
        static std::vector<std::any> _items;
};

// Special structure to reference keys with a compile time check
struct FStruct {
    static inline constexpr const char *didClickSaveText = "didClickSaveText";
    static inline constexpr const char *didLaunch = "didLaunch";
    static inline constexpr const char *didSelectTask = "didSelectTask";
    static inline constexpr const char *didSetup = "didSetup";
    static inline constexpr const char *isVisible = "isVisible";
    static inline constexpr const char *none = "none";
    static inline constexpr const char *saveString = "saveString";
    static inline constexpr const char *shouldSavaTasks = "shouldSavaTasks";
    static inline constexpr const char *taskTitle = "taskTitle";
    static inline constexpr const char *tasks = "tasks";

};
inline FStruct F;

// Special structure to reference keys in QML
class FObj: public QObject {
    Q_OBJECT
    Q_PROPERTY(QString didClickSaveText READ key_didClickSaveText CONSTANT)
    Q_PROPERTY(QString didLaunch READ key_didLaunch CONSTANT)
    Q_PROPERTY(QString didSelectTask READ key_didSelectTask CONSTANT)
    Q_PROPERTY(QString didSetup READ key_didSetup CONSTANT)
    Q_PROPERTY(QString isVisible READ key_isVisible CONSTANT)
    Q_PROPERTY(QString none READ key_none CONSTANT)
    Q_PROPERTY(QString saveString READ key_saveString CONSTANT)
    Q_PROPERTY(QString shouldSavaTasks READ key_shouldSavaTasks CONSTANT)
    Q_PROPERTY(QString taskTitle READ key_taskTitle CONSTANT)
    Q_PROPERTY(QString tasks READ key_tasks CONSTANT)


    public:
        FObj(): QObject() { }
        QString key_didClickSaveText() const { return F.didClickSaveText; }
        QString key_didLaunch() const { return F.didLaunch; }
        QString key_didSelectTask() const { return F.didSelectTask; }
        QString key_didSetup() const { return F.didSetup; }
        QString key_isVisible() const { return F.isVisible; }
        QString key_none() const { return F.none; }
        QString key_saveString() const { return F.saveString; }
        QString key_shouldSavaTasks() const { return F.shouldSavaTasks; }
        QString key_taskTitle() const { return F.taskTitle; }
        QString key_tasks() const { return F.tasks; }

};

#endif // KLIN_AUTOGENERATED_CPP_HEADER_H
